name: Publish

on:
  workflow_dispatch:
    inputs:
      ref:
        # require SHA as tags and branches are mutable
        description: Git commit SHA (not branch/tag)
        required: true
        type: string

env:
  FORCE_COLOR: 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Log inputs
        run: echo "${{ inputs }}"

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 2 # shouldn't need much, if any, history

      - name: Log Git tag
        run: git describe --always --tags

      - name: Check ref is the commit SHA
        # require SHA as tags and branches are mutable
        run: test "${{ inputs.ref }}"
          = "$(git git log --max-count=1 --format=format:%h)"
          || test "${{ inputs.ref }}"
          = "$(git git log --max-count=1 --format=format:%H)"

      # pipx is pre-installed in 'ubuntu' VMs

      - name: Provision nox environment
        run: pipx run nox --install-only

      - name: Build distribution via nox
        run: pipx run nox --no-install --error-on-missing-interpreters -s release_build

      - name: Upload distribution
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # 4.6.2
        with:
          name: packages
          path: dist/
          if-no-files-found: error
          compression-level: 0

  publish:
    needs:
    - build
    environment:
      name: pypi
      url: https://pypi.org/project/packaging/${{ github.ref_name }}
    permissions:
      id-token: write

    runs-on: ubuntu-latest

    steps:
      - name: Download distribution
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # 4.3.0
        with:
          name: packages
          path: dist/

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
        with:
          print-hash: true
