name: Publish

on:
  workflow_dispatch:
    inputs:
      ref:
        # require SHA as tags and branches are mutable
        description: Full git commit SHA (not branch/tag)
        required: true
        type: string

env:
  FORCE_COLOR: 1

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get-tag.outputs.tag }}

    steps:
      - name: Log inputs
        run: echo "${INPUTS}"
        env:
          INPUTS: ${{ toJSON(inputs)  }}

      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: ${{ inputs.ref }}
          persist-credentials: false
          fetch-depth: 0

      - name: Check ref is the commit SHA
        # require SHA as tags and branches are mutable
        run: test "${INPUTS_REF}"
          = "$(git log --max-count=1 --format=format:%h)"
          || test "${INPUTS_REF}"
          = "$(git log --max-count=1 --format=format:%H)"
        env:
          INPUTS_REF: ${{ inputs.ref }}

      - name: Get git tag
        id: get-tag
        run: echo "tag=$(git tag --points-at "$INPUTS_REF")" >> "$GITHUB_OUTPUT"
        env:
          INPUTS_REF: ${{ inputs.ref }}

      - name: Install nox with pbs
        run: pipx install nox[pbs]

      - name: Provision nox environment
        run: nox --install-only -s release_build

      - name: Build distribution via nox
        run: nox --no-install -R -s release_build

      - name: Upload distribution
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # 6.0.0
        with:
          name: packages
          path: dist/
          if-no-files-found: error
          compression-level: 0

  publish:
    needs:
      - build
    environment:
      name: pypi
      url: https://pypi.org/project/packaging/${{ needs.build.outputs.tag }}
    permissions:
      id-token: write
    # Only publish if there's a matching tag, and if this is not a fork
    if: needs.build.outputs.tag != '' && !github.event.repository.fork

    runs-on: ubuntu-latest

    steps:
      - name: Download distribution
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # 7.0.0
        with:
          name: packages
          path: dist/

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
        with:
          print-hash: true
