name: Test PyPy

on: [push]

jobs:
  test:
    name: Test ${{ matrix.pypy_version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python_version: ['pypy', 'pypy3']

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-python@v1
      name: Install ${{ matrix.pypy_version }}
      with:
        python-version: ${{ matrix.pypy_version }}
        # pypy for x64 not available from actions/setup-python@v1.
        architecture: 'x86'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r dev-requirements.txt

    - name: Run pytest
      run: python -m pytest --capture=no --strict
